config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: {
    in: %w[chinese italian japanese french belgian],
    message: '%<value> is not a valid category. Choose between the form options.'
    # check if %{} / %<> are interchangeable
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show] # add for each action (create)

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path(@restaurant)
  end
end

private

def set_restaurant
  @restaurant = Restaurant.find(params[:id])
end

def restaurant_params
  params.require(:restaurant).permit(:name, :category, :address, :phone_number)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# NAV BAR %>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <%= link_to "RailsYelpMvp!", restaurants_path, class: "navbar-brand fw-bold fs-3" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="#">Go premium</a>
            </li>
          </ul>
          <span class="navbar-text">
            <%= link_to "List a new resturant", new_restaurant_path, class: "ms-1 me-3 text-decoration-none fs-5 fw-bold" %>
          </span>
        </div>
      </div>
    </nav>

    <%# MAIN CONTENT %>
    <%= yield %>

    <%# FOOTER %>
    <div class="card text-start fixed-bottom">
      <div class="card-body">
        <a href="#" class="btn btn-sm btn-primary">Partner with us</a>
          <strong>@Made by a tired Wagoner</strong> ❤️
      </div>
   </div>
  </body>
</html>

app/views/restaurants/_back.html.erb
<hr>
<%= link_to "Back to listings", restaurants_path, class: "text-decoration-none fw-bold fs-5 text-primary" %>

app/views/restaurants/_form.html.erb
<div class="container mt-2 p-2 rounded bg-dark text-light align-middle fs-5">
    <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :category %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.submit "Submit listing", class: "btn btn-light fw-bold" %>
    <% end %>
  </div>
<%= render "back" %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
  <hr class="mb-0 border border-primary">
  <div class="container mt-3">
    <% @restaurants.each do |restaurant| %>
      <div class="border-bottom border-2 mb-3">
        <h4 class="mb-0"><%= link_to restaurant.name, restaurant_path(restaurant), class: "text-decoration-none text-dark" %></h4>
        <p class="text-danger"><em><strong><%= restaurant.category.capitalize %></strong></em></p>
        <p class="ms-1 fs-5"><strong>To reserve:</strong> <%= link_to restaurant.phone_number, "https://www.youtube.com/watch?v=xvFZjo5PgG0", class: "text-decoration-none fw-bold fs-5" %></p>
        <p class="ms-1 "><%= restaurant.address %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1 class="fw-bold">New restaurant listing</h1>
  <hr class="border border-danger">
  <%= render "form", restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <hr class="border border-danger">
  <div class="row mt-2 p-2 rounded bg-dark text-light align-middle fs-3 fw-bold">
    <p class="m-0">"<u><i>The best <%= @restaurant.category %> food</u></i>" in <%= @restaurant.address.match(/(?<=, ).*/) %>!</p>
  </div>
  <div class="container text-end fs-6">
    <p class="mb-0"><%= @restaurant.address %></p>
    <p class="mb-0"><%= @restaurant.phone_number %></p>
  </div>
  <h3 class="pb-1 border-bottom border-3 border-warning w-80">Reviews</h3>
  <div class="container mb-1 p-0"  style="--bs-bg-opacity: .35;">
    <% @restaurant.reviews.each do |review| %>
      <div class="bg-warning rounded">
      <p class="p-1 mb-0"><strong>Rating:</strong> <%= review.rating %></p>
      <p class="p-1 mb-2"><strong>Review:</strong> <%= review.content %></p>
      </div>
    <% end %>
    <%= link_to "Add your review", new_restaurant_review_path(@restaurant), class: "text-decoration-none fw-bold fs-5 text-dark" %>
  </div>
  <%= render "back" %>
</div>

app/views/reviews/_back.html.erb
<hr>
<%= link_to "Back to restaurant", restaurant_path(@restaurant), class: "text-decoration-none fw-bold fs-5 text-light" %>

app/views/reviews/new.html.erb
<div class="container">
  <h1 class="fw-bold">Add your review for <%= @restaurant.name %></h1>
  <hr class="border border-danger">
  <div class="container mt-2 p-2 rounded bg-dark text-light align-middle fs-5">
    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :rating, as: :numeric %>
      <%= f.input :content %>
      <%= f.submit "Submit review", class: "btn btn-light  fw-bold" %>
    <% end %>
    <%= render "back" %>
</div>
</div>